[09/Jan/2016 14:20:01] DEBUG [django_select2:98] Django found.
[09/Jan/2016 14:20:01] DEBUG [django_select2:132] Django found and fields and widgets loaded.
[09/Jan/2016 14:20:04] INFO [axes.watch_login:79] AXES: BEGIN LOG
[09/Jan/2016 14:20:04] INFO [axes.watch_login:80] Using django-axes 1.3.9
[09/Jan/2016 14:20:04] WARNING [app.goal.views:162] Ошибка при сохранении
Traceback (most recent call last):
  File "/my/web_projects/source/work_together/app/goal/views.py", line 159, in form_valid
    t.r = 8
NameError: global name 't' is not defined
[09/Jan/2016 14:21:45] DEBUG [django_select2:98] Django found.
[09/Jan/2016 14:21:45] DEBUG [django_select2:132] Django found and fields and widgets loaded.
[09/Jan/2016 14:21:46] INFO [axes.watch_login:79] AXES: BEGIN LOG
[09/Jan/2016 14:21:46] INFO [axes.watch_login:80] Using django-axes 1.3.9
[09/Jan/2016 14:21:52] DEBUG [django_select2:98] Django found.
[09/Jan/2016 14:21:52] DEBUG [django_select2:132] Django found and fields and widgets loaded.
[09/Jan/2016 14:21:56] INFO [axes.watch_login:79] AXES: BEGIN LOG
[09/Jan/2016 14:21:56] INFO [axes.watch_login:80] Using django-axes 1.3.9
[09/Jan/2016 14:24:25] DEBUG [django_select2:98] Django found.
[09/Jan/2016 14:24:25] DEBUG [django_select2:132] Django found and fields and widgets loaded.
[09/Jan/2016 14:24:26] INFO [axes.watch_login:79] AXES: BEGIN LOG
[09/Jan/2016 14:24:26] INFO [axes.watch_login:80] Using django-axes 1.3.9
[09/Jan/2016 14:25:08] DEBUG [django_select2:98] Django found.
[09/Jan/2016 14:25:08] DEBUG [django_select2:132] Django found and fields and widgets loaded.
[09/Jan/2016 14:25:12] INFO [axes.watch_login:79] AXES: BEGIN LOG
[09/Jan/2016 14:25:12] INFO [axes.watch_login:80] Using django-axes 1.3.9
[09/Jan/2016 14:25:18] ERROR [django.request:256] Internal Server Error: /goals/1/
Traceback (most recent call last):
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 272, in post
    return super(BaseUpdateView, self).post(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/my/web_projects/source/work_together/app/goal/views.py", line 158, in form_valid
    t.r = 8
NameError: global name 't' is not defined
[09/Jan/2016 14:25:18] ERROR [django.request:256] Internal Server Error: /goals/1/
Traceback (most recent call last):
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 272, in post
    return super(BaseUpdateView, self).post(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/my/web_projects/source/work_together/app/goal/views.py", line 158, in form_valid
    t.r = 8
NameError: global name 't' is not defined
[09/Jan/2016 14:25:18] ERROR [django.request:256] Internal Server Error: /goals/1/
Traceback (most recent call last):
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 272, in post
    return super(BaseUpdateView, self).post(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/my/web_projects/source/work_together/app/goal/views.py", line 158, in form_valid
    t.r = 8
NameError: global name 't' is not defined
[09/Jan/2016 14:26:26] DEBUG [django_select2:98] Django found.
[09/Jan/2016 14:26:26] DEBUG [django_select2:132] Django found and fields and widgets loaded.
[09/Jan/2016 14:26:41] INFO [axes.watch_login:79] AXES: BEGIN LOG
[09/Jan/2016 14:26:41] INFO [axes.watch_login:80] Using django-axes 1.3.9
[09/Jan/2016 14:28:56] DEBUG [django_select2:98] Django found.
[09/Jan/2016 14:28:56] DEBUG [django_select2:132] Django found and fields and widgets loaded.
[09/Jan/2016 14:28:59] INFO [axes.watch_login:79] AXES: BEGIN LOG
[09/Jan/2016 14:28:59] INFO [axes.watch_login:80] Using django-axes 1.3.9
[09/Jan/2016 14:29:00] ERROR [django.request:256] Internal Server Error: /goals/1/
Traceback (most recent call last):
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 272, in post
    return super(BaseUpdateView, self).post(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/my/web_projects/source/work_together/app/goal/views.py", line 158, in form_valid
    t.r = 8
NameError: global name 't' is not defined
[09/Jan/2016 14:29:00] ERROR [django.request:256] Internal Server Error: /goals/1/
Traceback (most recent call last):
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 272, in post
    return super(BaseUpdateView, self).post(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/my/web_projects/source/work_together/app/goal/views.py", line 158, in form_valid
    t.r = 8
NameError: global name 't' is not defined
[09/Jan/2016 14:29:00] ERROR [django.request:256] Internal Server Error: /goals/1/
Traceback (most recent call last):
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 272, in post
    return super(BaseUpdateView, self).post(request, *args, **kwargs)
  File "/home/volgoweb/.virtualenvs/wt/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/my/web_projects/source/work_together/app/goal/views.py", line 158, in form_valid
    t.r = 8
NameError: global name 't' is not defined
[09/Jan/2016 14:32:30] DEBUG [django_select2:98] Django found.
[09/Jan/2016 14:32:30] DEBUG [django_select2:132] Django found and fields and widgets loaded.
[09/Jan/2016 14:32:31] INFO [axes.watch_login:79] AXES: BEGIN LOG
[09/Jan/2016 14:32:31] INFO [axes.watch_login:80] Using django-axes 1.3.9
[09/Jan/2016 14:33:13] DEBUG [django_select2:98] Django found.
[09/Jan/2016 14:33:13] DEBUG [django_select2:132] Django found and fields and widgets loaded.
[19/Jan/2016 18:15:39] INFO [axes.watch_login:82] AXES: BEGIN LOG
[19/Jan/2016 18:15:39] INFO [axes.watch_login:83] Using django-axes 1.6.0
[20/Jan/2016 21:31:18] INFO [axes.watch_login:82] AXES: BEGIN LOG
[20/Jan/2016 21:31:18] INFO [axes.watch_login:83] Using django-axes 1.6.0
[20/Jan/2016 21:32:37] INFO [axes.watch_login:82] AXES: BEGIN LOG
[20/Jan/2016 21:32:37] INFO [axes.watch_login:83] Using django-axes 1.6.0
[20/Jan/2016 21:45:35] INFO [axes.watch_login:82] AXES: BEGIN LOG
[20/Jan/2016 21:45:35] INFO [axes.watch_login:83] Using django-axes 1.6.0
[20/Jan/2016 21:45:35] ERROR [django.request:256] Internal Server Error: /goals/my-goals/
Traceback (most recent call last):
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 103, in render_compressed
    rendered_output = compressor.output(mode, forced=forced)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/css.py", line 49, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/base.py", line 292, in output
    output = '\n'.join(self.filter_input(forced))
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/base.py", line 232, in filter_input
    for hunk in self.hunks(forced):
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/base.py", line 204, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/base.py", line 265, in precompile
    return True, filter.input(**kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/filters/base.py", line 229, in input
    return super(CachedCompilerFilter, self).input(**kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/filters/base.py", line 196, in input
    raise FilterError(err)
FilterError: /bin/sh: 1: lessc: not found

[20/Jan/2016 21:45:35] ERROR [django.request:256] Internal Server Error: /goals/my-goals/
Traceback (most recent call last):
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 103, in render_compressed
    rendered_output = compressor.output(mode, forced=forced)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/css.py", line 49, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/base.py", line 292, in output
    output = '\n'.join(self.filter_input(forced))
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/base.py", line 232, in filter_input
    for hunk in self.hunks(forced):
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/base.py", line 204, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/base.py", line 265, in precompile
    return True, filter.input(**kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/filters/base.py", line 229, in input
    return super(CachedCompilerFilter, self).input(**kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/filters/base.py", line 196, in input
    raise FilterError(err)
FilterError: /bin/sh: 1: lessc: not found

[20/Jan/2016 21:45:35] ERROR [django.request:256] Internal Server Error: /goals/my-goals/
Traceback (most recent call last):
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 103, in render_compressed
    rendered_output = compressor.output(mode, forced=forced)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/css.py", line 49, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/base.py", line 292, in output
    output = '\n'.join(self.filter_input(forced))
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/base.py", line 232, in filter_input
    for hunk in self.hunks(forced):
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/base.py", line 204, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/base.py", line 265, in precompile
    return True, filter.input(**kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/filters/base.py", line 229, in input
    return super(CachedCompilerFilter, self).input(**kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/compressor/filters/base.py", line 196, in input
    raise FilterError(err)
FilterError: /bin/sh: 1: lessc: not found

[20/Jan/2016 21:46:37] INFO [axes.watch_login:82] AXES: BEGIN LOG
[20/Jan/2016 21:46:37] INFO [axes.watch_login:83] Using django-axes 1.6.0
[20/Jan/2016 22:13:03] INFO [axes.watch_login:82] AXES: BEGIN LOG
[20/Jan/2016 22:13:03] INFO [axes.watch_login:83] Using django-axes 1.6.0
[20/Jan/2016 22:49:34] INFO [axes.watch_login:82] AXES: BEGIN LOG
[20/Jan/2016 22:49:34] INFO [axes.watch_login:83] Using django-axes 1.6.0
[20/Jan/2016 22:53:03] INFO [axes.watch_login:82] AXES: BEGIN LOG
[20/Jan/2016 22:53:03] INFO [axes.watch_login:83] Using django-axes 1.6.0
[20/Jan/2016 23:01:07] INFO [axes.watch_login:82] AXES: BEGIN LOG
[20/Jan/2016 23:01:07] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 08:34:56] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 08:34:56] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 08:36:26] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 08:36:26] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 08:49:17] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 08:49:17] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 08:51:50] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 08:51:50] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 08:52:57] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 08:52:57] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 10:15:58] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 10:15:58] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 20:46:22] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 20:46:22] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 20:54:14] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 20:54:14] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 21:00:43] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 21:00:43] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 21:01:48] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 21:01:48] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 21:01:49] ERROR [django.request:256] Internal Server Error: /goals/company-goals/
Traceback (most recent call last):
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/endless_pagination/views.py", line 99, in get
    self.object_list = self.get_queryset()
  File "/my/web_projects/source/work_together/app/goal/views.py", line 51, in get_queryset
    qs = self.get_base_queryset()
  File "/my/web_projects/source/work_together/app/goal/views.py", line 87, in get_base_queryset
    return Goal.objects.all().overdue().not_deleted().filter(performers__isnull=True).order_by('date_from')
AttributeError: 'GoalQueryset' object has no attribute 'overdue'
[21/Jan/2016 21:01:49] ERROR [django.request:256] Internal Server Error: /goals/company-goals/
Traceback (most recent call last):
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/endless_pagination/views.py", line 99, in get
    self.object_list = self.get_queryset()
  File "/my/web_projects/source/work_together/app/goal/views.py", line 51, in get_queryset
    qs = self.get_base_queryset()
  File "/my/web_projects/source/work_together/app/goal/views.py", line 87, in get_base_queryset
    return Goal.objects.all().overdue().not_deleted().filter(performers__isnull=True).order_by('date_from')
AttributeError: 'GoalQueryset' object has no attribute 'overdue'
[21/Jan/2016 21:01:49] ERROR [django.request:256] Internal Server Error: /goals/company-goals/
Traceback (most recent call last):
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/my/web_projects/source/virtualenv/wt/local/lib/python2.7/site-packages/endless_pagination/views.py", line 99, in get
    self.object_list = self.get_queryset()
  File "/my/web_projects/source/work_together/app/goal/views.py", line 51, in get_queryset
    qs = self.get_base_queryset()
  File "/my/web_projects/source/work_together/app/goal/views.py", line 87, in get_base_queryset
    return Goal.objects.all().overdue().not_deleted().filter(performers__isnull=True).order_by('date_from')
AttributeError: 'GoalQueryset' object has no attribute 'overdue'
[21/Jan/2016 21:02:39] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 21:02:39] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 21:16:04] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 21:16:04] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 21:26:01] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 21:26:01] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 21:29:38] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 21:29:38] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 21:32:19] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 21:32:19] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 21:33:29] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 21:33:29] INFO [axes.watch_login:83] Using django-axes 1.6.0
[21/Jan/2016 21:34:43] INFO [axes.watch_login:82] AXES: BEGIN LOG
[21/Jan/2016 21:34:43] INFO [axes.watch_login:83] Using django-axes 1.6.0
[22/Jan/2016 13:03:02] INFO [axes.watch_login:82] AXES: BEGIN LOG
[22/Jan/2016 13:03:02] INFO [axes.watch_login:83] Using django-axes 1.6.0
[22/Jan/2016 13:38:58] INFO [axes.watch_login:82] AXES: BEGIN LOG
[22/Jan/2016 13:38:58] INFO [axes.watch_login:83] Using django-axes 1.6.0
[22/Jan/2016 13:51:58] INFO [axes.watch_login:82] AXES: BEGIN LOG
[22/Jan/2016 13:51:58] INFO [axes.watch_login:83] Using django-axes 1.6.0
[22/Jan/2016 13:53:43] INFO [axes.watch_login:82] AXES: BEGIN LOG
[22/Jan/2016 13:53:43] INFO [axes.watch_login:83] Using django-axes 1.6.0
[22/Jan/2016 14:00:05] INFO [axes.watch_login:82] AXES: BEGIN LOG
[22/Jan/2016 14:00:05] INFO [axes.watch_login:83] Using django-axes 1.6.0
[22/Jan/2016 14:01:20] INFO [axes.watch_login:82] AXES: BEGIN LOG
[22/Jan/2016 14:01:20] INFO [axes.watch_login:83] Using django-axes 1.6.0
[22/Jan/2016 14:09:54] INFO [axes.watch_login:82] AXES: BEGIN LOG
[22/Jan/2016 14:09:54] INFO [axes.watch_login:83] Using django-axes 1.6.0
[24/Jan/2016 14:05:29] INFO [axes.watch_login:82] AXES: BEGIN LOG
[24/Jan/2016 14:05:29] INFO [axes.watch_login:83] Using django-axes 1.6.0
[24/Jan/2016 14:06:56] INFO [axes.watch_login:82] AXES: BEGIN LOG
[24/Jan/2016 14:06:56] INFO [axes.watch_login:83] Using django-axes 1.6.0
[24/Jan/2016 14:07:49] INFO [axes.watch_login:82] AXES: BEGIN LOG
[24/Jan/2016 14:07:49] INFO [axes.watch_login:83] Using django-axes 1.6.0
[24/Jan/2016 14:08:12] INFO [axes.watch_login:82] AXES: BEGIN LOG
[24/Jan/2016 14:08:12] INFO [axes.watch_login:83] Using django-axes 1.6.0
[24/Jan/2016 14:09:28] INFO [axes.watch_login:82] AXES: BEGIN LOG
[24/Jan/2016 14:09:28] INFO [axes.watch_login:83] Using django-axes 1.6.0
[24/Jan/2016 14:10:03] INFO [axes.watch_login:82] AXES: BEGIN LOG
[24/Jan/2016 14:10:03] INFO [axes.watch_login:83] Using django-axes 1.6.0
[24/Jan/2016 14:11:28] INFO [axes.watch_login:82] AXES: BEGIN LOG
[24/Jan/2016 14:11:28] INFO [axes.watch_login:83] Using django-axes 1.6.0
[24/Jan/2016 14:12:13] INFO [axes.watch_login:82] AXES: BEGIN LOG
[24/Jan/2016 14:12:13] INFO [axes.watch_login:83] Using django-axes 1.6.0
[24/Jan/2016 14:12:27] INFO [axes.watch_login:82] AXES: BEGIN LOG
[24/Jan/2016 14:12:27] INFO [axes.watch_login:83] Using django-axes 1.6.0
[24/Jan/2016 14:14:52] INFO [axes.watch_login:82] AXES: BEGIN LOG
[24/Jan/2016 14:14:52] INFO [axes.watch_login:83] Using django-axes 1.6.0
[24/Jan/2016 14:15:27] INFO [axes.watch_login:82] AXES: BEGIN LOG
[24/Jan/2016 14:15:27] INFO [axes.watch_login:83] Using django-axes 1.6.0
[24/Jan/2016 14:16:29] INFO [axes.watch_login:82] AXES: BEGIN LOG
[24/Jan/2016 14:16:29] INFO [axes.watch_login:83] Using django-axes 1.6.0
[24/Jan/2016 14:18:02] INFO [axes.watch_login:82] AXES: BEGIN LOG
[24/Jan/2016 14:18:02] INFO [axes.watch_login:83] Using django-axes 1.6.0
[24/Jan/2016 14:18:38] INFO [axes.watch_login:82] AXES: BEGIN LOG
[24/Jan/2016 14:18:38] INFO [axes.watch_login:83] Using django-axes 1.6.0
